[package]
name = "rust-token-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.5"
rangemap = "1.3.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v4"]
